### ISSUE TITLE
enhancement:enhance random stream.

### ISSUE THREAD

**Issue by lizhou1111** [timeplus-io/proton#103]
1. Let events be evenly distributed over one second.You can specify the time interval.For example CREATE RANDOM STREAM rand_stream(i int default rand()%5) SETTINGS eps=1000, interval_time=100; means generating equal amount of data for each interval(eps / (1000 / interval_time)).  
2. fixed the bug when creating random stream with unknown settings the proton-server will core-dump  
3. add random stream smoke test

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by yl-lisen** [comment]
closed by #103
