### ISSUE TITLE
update release image tag with suffix '-rc'

### ISSUE THREAD

**Issue by qijun-niu-timeplus** [timeplus-io/proton#125]
**Use case**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qijun-niu-timeplus** [comment]
https://github.com/timeplus-io/proton/pull/126

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
done in sprint52

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
