### ISSUE TITLE
clean typo in tests json

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#133]
**Use Case**

Our smoke tests currently use a Python script to execute a JSON test suite. When specifying a query that needs automatic shutdown, the script checks for `"terminate": "auto"` in the JSON phase. The detailed script logic for checking `"terminate"` is in this code:
https://github.com/timeplus-io/proton/blob/057bfda9c9584f5ed6dc874d30e4fa2fcea9aafe/tests/stream/helpers/rockets.py#L2865-L2870

The issue is that our JSON contains a typo for terminate:

https://github.com/timeplus-io/proton/blob/057bfda9c9584f5ed6dc874d30e4fa2fcea9aafe/tests/stream/test_stream_smoke/0009_stream_join_stream_case2.json#L21

It has `"manuel"` instead of `"manual"`.

**Proposed Solution**

We should clean up the related Python script as well. The default condition only checks for `"auto"`, so we are currently skipping over this typo.

**Comment by varshneydevansh** [comment]
is this line related to this?  

https://github.com/timeplus-io/proton/blob/057bfda9c9584f5ed6dc874d30e4fa2fcea9aafe/tests/stream/helpers/rockets.py#L1506

I have made the typo changes to the smoke tests json files.

**Comment by yokofly** [comment]
> is this line related to this?
> 
> https://github.com/timeplus-io/proton/blob/057bfda9c9584f5ed6dc874d30e4fa2fcea9aafe/tests/stream/helpers/rockets.py#L1506
> 
> I have made the typo changes to the smoke tests json files.

Hi, this line is unrelated. thanks!
