### ISSUE TITLE
Support ipv4 and ipv6 data type

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/proton#142]
for web analytics, IP address is a very common data type. refer to https://clickhouse.com/blog/geolocating-ips-in-clickhouse-and-grafana.

- https://clickhouse.com/docs/en/sql-reference/data-types/ipv4
- https://clickhouse.com/docs/en/sql-reference/data-types/ipv6

it is better to have such type support in proton

**Comment by gangtao** [comment]
with following queries, the `to_ipv4` does not support number input, string input works

```sql
select to_ipv4(16777216::uint64)
select to_ipv4('127.0.0.1')
```

clickhouse works
![image](https://github.com/timeplus-io/proton/assets/3509037/e2a88e6c-e3f1-4c6b-b45b-c16e5faacfec)

**Comment by gangtao** [comment]
according to @yl-lisen , we can use `ipv4_num_to_string`

**Comment by jovezhong** [comment]
Please see more discussions at https://github.com/timeplus-io/proton/issues/141#issuecomment-1754412300

ipv4 and ipv6 already working in Proton, but need to add documentation and UI refinements(for Timeplus Cloud)

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
Close this, since the docs.timeplus.com has been updated.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
