### ISSUE TITLE
[CI] Mark a stable image from release candidate

### ISSUE THREAD

**Issue by leo-cai-timeplus** [timeplus-io/proton#148]
**Use case**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
It's okay for the CI to only generate `.-rc` tag
and after manual verification, a developer to add a new tag to ghcr.io without the rc. For example
1.3.20-rc is generate by CI

After tests, someone adds a new tag `1.3.20` to the same image. Our deployment script will use 1.3.20 as the tag for Timeplus Cloud update. 

CC @leo-cai-timeplus ,  @qijun-niu-timeplus  @jhao0117  @chenziliang  @gangtao @zliang-min
