### ISSUE TITLE
Replay a stream

### ISSUE THREAD

**Issue by chenziliang** [timeplus-io/proton#163]
**Use case**

As a user, I would like to replay a stream or several streams at the speed when the events were generated. 

For example for query like below, we rewind the data to one day ago and replay the events in stock_prices stream at the (relatively) same speed when the events got generated. When the replay catches up to the live events, handle the events at the live speed.

```
SELECT * FROM stock_prices WHERE _tp_time > now() - 1d settings replay_speed=1;
```

**Describe the solution you'd like**

We probably need introduce something like a `RateLimitTransform` to plugin into the pipeline after SourceReader or a direct `RateLimitReader` to control the replay speed. The RateLimitTransform can buffer some events and control the replay speed according to the `_tp_append_time` of events.

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by yl-lisen** [comment]
Phase 1: #224, support replay a stream. Done
Phase 2: Enhancement: disable replay when reached latest data 
@lizhou1111

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
