### ISSUE TITLE
Mac users is able to `brew install proton` 

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#164]
**Use case**

Today we provide docker images for Proton. As the next step, it will be easier for developer using MacOS to install and upgrade proton via homebrew

**Describe the solution you'd like**

`brew install proton` to install proton
`brew upgrade` to upgrade proton to latest version

Work for both intel and arm Mac

**Additional context**

Prereq : #94

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by yokofly** [comment]
clean github issue list
https://github.com/timeplus-io/homebrew-timeplus
