### ISSUE TITLE
show changelogs for new proton github tags/releases

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#165]
There is no changelog or a list of merged PR in the proton release or tag
https://github.com/timeplus-io/proton/releases/tag/v1.3.14

Open source users are expecting to see such changelogs.

Please refer to axion/neutorn CI process.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by yokofly** [comment]
after https://github.com/timeplus-io/proton/pull/269
changelog in the release asset display normally. (automatically generated)
https://github.com/timeplus-io/proton/pull/269/files#diff-f9cb62ec2ff97fce91a3cdefb34fecb45bd54fe32ca3e3aaa454905d7710aa59R169
