### ISSUE TITLE
nightly test doesn't remove testing image after test pass

### ISSUE THREAD

**Issue by qijun-niu-timeplus** [timeplus-io/proton#168]
**Describe what's wrong**

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
There are still a lot of test images ought to be deleted.

<img width="1014" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/1f8e0c64-b122-4c1e-afdd-79dfcc38c541">

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
