### ISSUE TITLE
Two level hash table revisit

### ISSUE THREAD

**Issue by chenziliang** [timeplus-io/proton#185]
**Use case**

So far for global aggregation, if we auto scale to two level hash table, it is not correctly handled.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenziliang** [comment]
Related to https://github.com/timeplus-io/proton-enterprise/issues/1449

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
