### ISSUE TITLE
Shard strategy for Kafka Sink

### ISSUE THREAD

**Issue by chenziliang** [timeplus-io/proton#192]
**Use case**

As a user, i would like to shard the data to my Kafka topic according to some sharding expression when sink to it.

**Describe the solution you'd like**

```
CREATE EXTERNAL STREAM sharded_external_stream 
(raw string, id string)
SETTINGS sharding_expr=hash(id);
```

https://github.com/timeplus-io/proton/blob/develop/src/Storages/MergeTree/MergeTreeSettings.h#L171
https://github.com/timeplus-io/proton/blob/develop/src/Storages/Streaming/StreamSink.cpp#L55-L84

**Describe alternatives you've considered**

**Additional context**

**Comment by chenziliang** [comment]
We calculate an integer according to `sharding_expr` and pass the integer as partition key to librdkafka

**Comment by zliang-min** [comment]
There are two things for sharding/paritioning:
1. just use a message key. Kafka will make sure messages with the same key will be stored in the same partition.
2. calculate the parition ID directly. We can assign a partitioner function and let it to calculate the partition ID for the messages.

For now, I think using message key should be enough for most cases. I would like to separate the implementation for `2` in another ticket (when it's needed, and in fact, in the example of this ticket `hash(id)`, it does not look like it will generate a partition ID, it just says it wants to use `id` as the message key).

And for speicifying message key, I suggest we use a setting called `message_key` ( or `sharding_key` sounds fine to me too ).

@chenziliang any objection?

**Comment by chenziliang** [comment]
sharding could depend on multiple columns or an expression like a function. If we need leverage kafka message key , we will need allocate memory and copy over the `key columns` and for expression, we still need evaluate it first and then copy over.

So above sharding expression doesn't calculate a partition ID or shard ID, it just produce an integer. We can pass the integer to Kafka as the partition key i think things will just work.

**Comment by zliang-min** [comment]
Message key is a string, so the expression should generate a string, not an integer, thus the expression should return a string, and we should not do any implicite converstion.

**Comment by chenziliang** [comment]
the expression shall return an integer

**Comment by chenziliang** [comment]
we can cast the integer before passing it to libradkafka or just use the integer to assign a partition by ourselves which is also easy.

**Comment by sunset3000** [comment]
> There are two things for sharding/paritioning:
> 
> 1. just use a message key. Kafka will make sure messages with the same key will be stored in the same partition.
> 2. calculate the parition ID directly. We can assign a partitioner function and let it to calculate the partition ID for the messages.
> 
> For now, I think using message key should be enough for most cases. I would like to separate the implementation for `2` in another ticket (when it's needed, and in fact, in the example of this ticket `hash(id)`, it does not look like it will generate a partition ID, it just says it wants to use `id` as the message key).
> 
> And for speicifying message key, I suggest we use a setting called `message_key` ( or `sharding_key` sounds fine to me too ).
> 
> @chenziliang any objection?

I think step 1 that proton provides a message key is enough for now. Let us try to implement this first.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
