### ISSUE TITLE
Checkpoint file not found

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#226]
**Describe what's wrong**

Recently ( I don't really have a concret timeline though, I think it's since we upgraded to 1.3.13 ), we are seeing a lot of checkpoint file not found error like this
```
2023.10.27 18:06:28.799544 [ 2676 ] {} <Error> StorageMaterializedView (default.`sink_34d8f4d7-c2ef-4c3e-bcd9-f47e83cf583a`): FILE_DOESNT_EXIST: Wait for 36300th recovering background pipeline of matierialized view 'default.`sink_34d8f4d7-c2ef-4c3e-bcd9-f47e83cf583a`'. Background runtime error: Cannot open file /var/lib/proton/checkpoint/.inner.query-id.from-d9b9995f-016d-4fab-8b4a-b3cb7c1ff6e2/dag.ckpt, errno: 2, strerror: No such file or directory (Background status: EXECUTING_PIPELINE)
```

Even after I cleaned up the checkpoint folders, and restarted proton, such errors showed up again after some time. I think we should take a closer look and see if we can find out what's the root cause and fix it.

Further more, I wonder if we can make proton automatically recover from such failure? Because when someone encounters such error, they won't be able to query the MV anymore.

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by yl-lisen** [comment]
Close first, will continue to pay attention
