### ISSUE TITLE
External stream supports security.protocol=sasl_plaintext

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#250]
**Use case**

We got a community user who configured the Redpanda with security.protocol=sasl_plaintext

We need to enhance External Stream to read/write to such server.

kcat command
```
kcat -b 1.2.3.4:9093 -X security.protocol=sasl_plaintext -X sasl.mechanisms=SCRAM-SHA-256 -X sasl.username=abc -X sasl.password=xyz -L
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zliang-min** [comment]
This should have been implemented with this commit: https://github.com/timeplus-io/proton/commit/41c2e5c406bf0d01aeeaec55458b6820d6178b42

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
