### ISSUE TITLE
aggregation result support changelog mode

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#27]
**Describe what's wrong**

edit 1:
Currently recommended to write a versioned_kv table, but versioned_kv not support deletion, the changelog is more appropriate, but the result does not work with changelog mode.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
