### ISSUE TITLE
telemetry: generate a unique ID for the deployment (per database or server)

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#281]
**Describe what enhancement you'd like to have**

When the telemetry is enabled, currently we generate a unique session id. However if the user stops and starts Proton over time, we cannot track whether it's the same user. The session ID is different, and the external IP could change too. As a result, we noticed a lot of unique ID, not sure how many OSS users behind.

When the proton starts for the first time, when you create the default database, please also generate a unique ID for the server, or for this `default` database, and report telemetry data with that ID.

**Comment by chenziliang** [comment]
We have server UUID, we can use that. This is the best we can do for now.

**Comment by jovezhong** [comment]
PR merged https://github.com/timeplus-io/proton/pull/304
