### ISSUE TITLE
using seek_to with specify timestamp in external stream  can't work

### ISSUE THREAD

**Issue by lizhou1111** [timeplus-io/proton#287]
```sql
-- redpanda
-- rpk topic create test -p 3

-- proton1 
drop stream if exists test_external1;
create external stream if not exists test_external1(id int, value string) settings type = 'kafka', brokers = 'redpanda-1:9092', topic = 'test', data_format='JSONEachRow';

-- redpanda
-- rpk topic produce test
{"id":1,"value":"sometext"}
Produced to partition 0 at offset 2 with timestamp 1700015474271.
{"id":2,"value":"aaaaa"}
Produced to partition 2 at offset 1 with timestamp 1700015492170.
{"id":3,"value":"bbbbb"}
Produced to partition 1 at offset 1 with timestamp 1700015510566.
{"id":4,"value":"ccccc"}
Produced to partition 2 at offset 2 with timestamp 1700015528830.
-- proton
select * from test_external1 settings seek_to='2023-11-11 14:15:24.219';

```

**Comment by zliang-min** [comment]
Kafka and alike don't have good support for seeking for a specific timestamp. I don't think we should support this in external streams. Please let me know if you think differently @chenziliang @jovezhong

**Comment by chenziliang** [comment]
Kafka can seek via timestamp. The timestamp can be server side append time by default or application assigned time if I recalled it correctly. But in general, they could be different than _tp_time (event time)

**Comment by zliang-min** [comment]
I think you mean  `rd_kafka_offsets_for_times()`? My understanding is that it uses messages' timestamps, which could be event time or ingest time. So do we want seek_to works in that way? If so, I have a follow up question, should we generate the `_tp_time` field for each kafka message using the message's timestamp too? I think that's reasonable if we allow using seek_to with timestamps.

**Comment by chenziliang** [comment]
https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message and https://github.com/timeplus-io/proton/blob/develop/src/KafkaLog/KafkaWALCommon.cpp#L234-L277

**Comment by chenziliang** [comment]
That was what i read quite a long time back.

**Comment by chenziliang** [comment]
If we like to support seek_to for external stream, this is the best thing we can do since we don't control the timestamp, end users do. We just need document what it means. 

I would suggest deferring this feature a bit since no customer requirements so far.

**Comment by jhao0117** [comment]
seek_to='earliest' looks good but specifying a timestamp does not work, @lizhou1111 , please add your verification result here.

**Comment by zliang-min** [comment]
Duplicates #345
