### ISSUE TITLE
SQL Format error, it shows __subquery_id after formatting the SQL

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#327]
**Describe what's wrong**

This is triggered by Timeplus Cloud UI, but should be a proton bug.

The SQL I tried to format is 
```sql
select date_diff('second',(select max(_tp_time) from table(car_live_data)),_tp_time) from car_live_data limit 1
```
Proton will generate this as 
```sql
SELECT 
  date_diff('second', __subquery_8470409168922555722_14136957409797182278, _tp_time)
FROM 
  car_live_data
LIMIT 1
```

**How to reproduce**
You can try this in demo.timeplus.cloud. I also found this issue in 1.3.15 proton

**Error message and/or stacktrace**

**Additional context**

**Comment by yl-lisen** [comment]
It's a default subquery name, i think we should use a alias as follows:
```sql
select date_diff('second',(select max(_tp_time) from table(car_live_data)) as max_time,_tp_time) from car_live_data limit 1

SELECT 
  date_diff('second', max_time, _tp_time)
FROM 
  car_live_data
LIMIT 1
```

or 
```sql
with (select max(_tp_time) from table(car_live_data)) as max_time select date_diff('second', max_time ,_tp_time) from car_live_data limit 1

WITH (
    SELECT 
      max(_tp_time)
    FROM 
      table(car_live_data)
  ) AS max_time
SELECT 
  date_diff('second', max_time, _tp_time)
FROM 
  car_live_data
LIMIT 1
```

**Comment by yl-lisen** [comment]
There is no need to adjust this behavior
@jovezhong

**Comment by jovezhong** [comment]
The problem is after formatting the SQL, the SQL is not runnable, due the lack of definition of the subquery

**Comment by yl-lisen** [comment]
> The problem is after formatting the SQL, the SQL is not runnable, due the lack of definition of the subquery

got it, will fix it as soon
