### ISSUE TITLE
when huge block size exceeds the max message size of kafka/redpanda, the huge block  can't insert into external stream

### ISSUE THREAD

**Issue by lizhou1111** [timeplus-io/proton#335]
huge block can't insert into external stream.
Below is the python script to insert buge block into redpanda.
```python
from proton_driver import client

one_data = [1,2,3,4]

# proton
# drop stream if exists test_stream2;
# create external stream if not exists test_stream2(
# 	a int8,
# 	b int16,
# 	c int32,
# 	d int64
# 	)settings type = 'kafka', brokers = 'redpanda-1:9092', topic = 'test',data_format='JSONEachRow' ;

def GenerateCase(count):
    rows = []
    for i in range(count):
        
        row = one_data.copy()
        row[3] = i
        # to tuple
        row = tuple(row)
        rows.append(row)
    
    return rows

if __name__ == "__main__":
    client = client.Client(host="127.0.0.1", port=8463)
    rows = GenerateCase(100000)
    # print(rows)
    client.execute("insert into test_stream2(a, b, c, d) values", rows)
```
The error message is `proton_driver.errors.ServerException: Code: 2600.
DB::Exception: Cannot write to kafka topic at offset 2097152, error: Broker: Message size too large. Stack trace:`

**Comment by zliang-min** [comment]
This is expected. We can add support for setting the `message.max.bytes` property when creating a external stream. However, a topic also has such configuration on the broker side. Thus, it is still possible being limited by the topic no matter how big the `message.max.bytes` value we set on the producer (the sink) side.
