### ISSUE TITLE
RefCountDataBlockPages / RefCountDataBlockList micro-benchmark

### ISSUE THREAD

**Issue by chenziliang** [timeplus-io/proton#336]
**Describe what enhancement you'd like to have**

RefCountDataBlockPages / RefCountDataBlockList micro-benchmark to see how the memory efficiency / perf looks like

**Comment by chenziliang** [comment]
Column's memory efficiency is v bad when we have single row. Some initial benchmark shows this metric.  For a 3 columns (datetime64, uint64, string 16 bytes) LightChunk with single row, the current code basically does

1.  Over allocated memory. for example, for a 8 byte uint64 integer, it allocates 256 bytes
2. The metadata also occupies quite a few memory

```
root@t+ release-build % ./src/Interpreters/Streaming/benchmarks/data_blocks_perf --benchmark_filter=refCountDataBlockPages/Column3ChunkRows1Chunks1000000   
2023-11-26T07:42:44+00:00
Running ./src/Interpreters/Streaming/benchmarks/data_blocks_perf
Run on (32 X 2799.99 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 512 KiB (x16)
  L3 Unified 16384 KiB (x4)
Load Average: 5.48, 4.94, 8.82
allocated_bytes=1172 allocated_data_bytes=1024 allocated_metadata_bytes=148 raw_data_bytes=41
uint64 allocated_bytes=256 allocated_metadata_bytes=24 raw_data_bytes=8
datetime64 allocated_bytes=256 allocated_metadata_bytes=28 raw_data_bytes=8
string allocated_bytes=512 allocated_metadata_bytes=48 raw_data_bytes=25
data_blocks=1954 metrics={total_bytes=1172000000 total_blocks=1000000 current_total_bytes=1172000000 current_total_blocks=1000000 gced_blocks=0}
...
```

**Comment by chenziliang** [comment]
BlockPages doesn't help much if the column level memory inefficiency is not resolved for streaming case.

**Comment by yl-lisen** [comment]
> Column's memory efficiency is v bad when we have single row. Some initial benchmark shows this metric. For a 3 columns (datetime64, uint64, string 16 bytes) LightChunk with single row, the current code basically does
> 
> 1. Over allocated memory. for example, for a 8 byte uint64 integer, it allocates 256 bytes
> 2. The metadata also occupies quite a few memory
> 
> ```
> root@t+ release-build % ./src/Interpreters/Streaming/benchmarks/data_blocks_perf --benchmark_filter=refCountDataBlockPages/Column3ChunkRows1Chunks1000000   
> 2023-11-26T07:42:44+00:00
> Running ./src/Interpreters/Streaming/benchmarks/data_blocks_perf
> Run on (32 X 2799.99 MHz CPU s)
> CPU Caches:
>   L1 Data 32 KiB (x16)
>   L1 Instruction 32 KiB (x16)
>   L2 Unified 512 KiB (x16)
>   L3 Unified 16384 KiB (x4)
> Load Average: 5.48, 4.94, 8.82
> allocated_bytes=1172 allocated_data_bytes=1024 allocated_metadata_bytes=148 raw_data_bytes=41
> uint64 allocated_bytes=256 allocated_metadata_bytes=24 raw_data_bytes=8
> datetime64 allocated_bytes=256 allocated_metadata_bytes=28 raw_data_bytes=8
> string allocated_bytes=512 allocated_metadata_bytes=48 raw_data_bytes=25
> data_blocks=1954 metrics={total_bytes=1172000000 total_blocks=1000000 current_total_bytes=1172000000 current_total_blocks=1000000 gced_blocks=0}
> ...
> ```

This is a good benchmark test that let's know what needs further optimization. And we need to do more things like this later.

**Comment by chenziliang** [comment]
Closed in https://github.com/timeplus-io/proton/pull/337
