### ISSUE TITLE
External Stream supports read/write Apache Pulsar

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#338]
**Use case**

Essentially we are building the best streaming SQL engine for live data. Apache Kafka and API-compatiable streaming platforms are well supported in Proton and Timeplus Cloud.

Currently [Apache Pulsar](https://pulsar.apache.org) is supported in Timeplus Cloud via other components. It will be great to have Proton support Apache Pulsar out of box. One workaround is to using KoP(Kafka on Pulsar) but native integration with Apache Pulsar is preferred. 

We welcome the community to contribute more integrations for Proton with other systems. This ticket is specifically about the integration with Apache Pulsar via Proton External Stream.

**Describe the solution you'd like**

Similar to https://docs.timeplus.com/proton-kafka, we expect the users can create an external stream to connect Proton with the Apache Pulsar deployment, such as
```sql
CREATE EXTERNAL STREAM [IF NOT EXISTS] stream_name (<col_name1> <col_type>)
SETTINGS type='pulsar', brokers='ip:port',topic='..',security_protocol='..',username='..',password='..',sasl_mechanism='..'
```

If this is applicable to Apache Pulsar, we expect various authentication and security protocols  are supported, just like our Kafka integration 

The supported values for security_protocol are:
* PLAINTEXT: when this option is omitted, this is also the default value.
* SASL_SSL: when this value is set, username and password should be specified.

The supported values for sasl_mechanism are:
* PLAIN: when you set security_protocol to SASL_SSL, this is the default value for sasl_mechanism.
* SCRAM-SHA-256
* SCRAM-SHA-512

It should supports both local deployment of Apache Pulsar or [StreamNative Cloud](https://streamnative.io/deployment/hosted).

Once the external stream for Apache Pulsar is created, the user can read from the stream to get existing or new messages in Pulsar, or write data to Pulsar.

Plaintext, Avro, Protobuf, JSON Schema format should be supported.

We should be able to read the entire message body as a string, or break them to multiple columns. Similar behavior/capabilities as the Kafka External Stream.

**Describe alternatives you've considered**

**Additional context**

Refer to https://docs.timeplus.com/proton-kafka to learn the expected feature set for the new external stream.

Refer to the Pulsar source/sink UI in Timeplus Cloud, e.g.
<img width="973" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/1e02afc8-803a-45bf-8c8d-69a4ce7d2fd7">

<img width="981" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/8bc00c54-c35b-4249-b644-f7b67bfa70d7">

<img width="938" alt="image" src="https://github.com/timeplus-io/proton/assets/5076438/a8e3d6ec-a933-4d34-a00d-7c2e1682ee17">

**Comment by Kartik1397** [comment]
Hi @jovezhong, I would like to work on this, can I pick this up?

/attempt #338

<div id="algora" />

| [Algora profile](https://console.algora.io/@/Kartik1397) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @Kartik1397 | 4 bounties from 3 projects | <div align="center">Ruby, TypeScript, <br />JavaScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clrqvwmo60008l00fro21x1nb/cancel-attempt) |

**Comment by jovezhong** [comment]
Sure, please go ahead, @Kartik1397 

You can join https://timeplus.com/slack (seems you just joined) and use #contributing channel to discuss the design or code change.

**Comment by Neustradamus** [comment]
To follow this ticket

**Comment by jovezhong** [comment]
Hi @Neustradamus , let me know whether you'd like to work on the development or wait to test this feature when it's ready.

**Comment by jovezhong** [comment]
After over 6 months waiting, there is no ready-to-review PR form the community so our team decided to cancel the bounty and implement it by ourselves. @zliang-min has been assigned to work on this, starting from now.

**Comment by jovezhong** [comment]
Closing the ticket, as we plan to build a MVP version of it in our commercial offering and get feedbacks
