### ISSUE TITLE
Support partial schema for JSONEachRow format with Kafka external streams

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#340]
**Use case**

When using `JSONEachRow` data format with Kafka external stream, if the stream schema does not have all the fields that the JSON messages have, for example, if the JSON messages have two fields, `a` and `b`, but only the `a` field is defined in the external stream, then when try to run a select query against that external stream it won't return anything back.

It will be convenient if it supports defining parital schema as the stream schema because not all the fields in the JSON messages are always useful in all cases.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by zliang-min** [comment]
The behavior is controlled by a setting called `input_format_skip_unknown_fields` which defaults to `false`, and here is the doc for the setting: `Skip columns with unknown names from input data (it works for JSONEachRow, -WithNames, -WithNamesAndTypes and TSKV formats).`.

So in order to make this work, one just need to do this:
```SQL
SELECT * FROM my_external_stream SETTINGS input_format_skip_unknown_fields=true
```

cc @jovezhong

**Comment by jovezhong** [comment]
But I tried true and 'true', neither of them work

```sql
CREATE EXTERNAL STREAM frontend_events_partial(
	version int,
	requestedUrl string,
	method string
)	
SETTINGS type='kafka', 
         brokers='redpanda:9092',
         topic='owlshop-frontend-events',
         data_format='JSONEachRow',
         input_format_skip_unknown_fields=true; 
```

**Comment by zliang-min** [comment]
No, you can't set it in CREATE STREAM, you need to set it in SELECT. Please check my previous comment.

**Comment by jovezhong** [comment]
Sorry, my bad. I verified it works. I will add to docs

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
