### ISSUE TITLE
proton crash by using embeded config when using grok

### ISSUE THREAD

**Issue by chenziliang** [timeplus-io/proton#346]
**Describe what's wrong**

config-less proton `proton server` will crash if we use grok function, this may related to grok regex file is not available and we didn't init grok global regex map correctly.

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by yokofly** [comment]
@chenziliang cannot reproduce locally, may you try the latest commit? or share the stacktrace or error sql?
the embed.xml needs removed from the build folder and rebuild. 
(simply rebuilding without removing the folder will not change the embedded content)
with c-cache, the build process is fast enough.

I tried below demo case below in [docs.timeplus.com](https://docs.timeplus.com/functions_for_text#grok), but all things worked correct 
```sql
 :) SELECT grok('My name is Jack. I am 23 years old.','My name is %{DATA:name}. I am %{INT:age} years old.') as m

SELECT 
  grok('My name is Jack. I am 23 years old.', 'My name is %{DATA:name}. I am %{INT:age} years old.') AS m

Query id: 9c56918c-1136-48b3-9032-007e0047a3cb

┌─m──────────────────────────┐
│ {'name':'Jack','age':'23'} │
└────────────────────────────┘

1 row in set. Elapsed: 0.026 sec. 

:) q
Bye.

```

below is the video on proton@1.3.24 published binary:
https://harvest-vegetarian-745.notion.site/grok-demo-on-proton-1-3-24-config-less-ver-cb78f022fe864a3db10207056d8c7255?pvs=4

**Comment by chenziliang** [comment]
I recalled i run our streaming test suite, it crashes. You can try run `python3 ci_runner.py --local` to reproduce it.

**Comment by yokofly** [comment]
> I recalled i run our streaming test suite, it crashes. You can try run `python3 ci_runner.py --local` to reproduce it.


I understand now. Previously, I thought that `config less` was only for trial purposes and not for production. That's why I didn't pay much attention to the smoke test failure.

**Comment by chenziliang** [comment]
Only run the grok test suites

**Comment by yokofly** [comment]
grok test suites cannot reproduce
I will try iterate the other test suite
```
 python3 ci_runner.py --local -q smoke1 -i 84
 ```

**Comment by yokofly** [comment]
cannot reproduce in proton release binary 1.3.25. say the smoke test failure 4 test cases. it's expected 
download the binary with this `curl -sSf https://raw.githubusercontent.com/timeplus-io/proton/develop/install.sh | sh`
or directly click the https://github.com/timeplus-io/proton/releases/tag/v1.3.25

```
=============================================================================== short test summary info ================================================================================
FAILED test_stream_smoke/test_query_smoke.py::test_run[privilege-0-create user_select_only, create role select_only, grant select_only role to user_select_only, create stream, drop stream fail and select success]
FAILED test_stream_smoke/test_query_smoke.py::test_run[seek_to-8-seek_to] - AssertionError: expected_result = [{'query_id': '2100', 'expected_results': [[3, 's3', '2022-12-01 00:00:...
FAILED test_stream_smoke/test_query_smoke.py::test_run[seek_to-10-seek_to] - AssertionError: expected_result = [{'query_id': '2100', 'expected_results': [['s1'], ['s3']]}, {'query_i...
FAILED test_stream_smoke/test_query_smoke.py::test_run[seek_to-13-seek_to] - AssertionError: expected_result = [{'query_id': '2100', 'expected_results': [['s1'], ['s2'], ['s3'], ['s...
====================================================================== 4 failed, 797 passed in 1184.22s (0:19:44) ======================================================================

```

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by yokofly** [comment]
recently work well with  release  binary , close to keep issue list clean.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
