### ISSUE TITLE
Fail to create materialized view in port 8123

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#363]
**Describe what's wrong**

All queries are in batch mode by default in port 8123. However I still expect I can create mv in this port. The error I am getting in DBeaver with 8123 JDBC port is

> SQL Error [80] [07000]: Code: 80. DB::Exception: Materialized view doesn't support historical select query. (INCORRECT_QUERY) (version 1.3.25)
> , server ProtonNode(addr=http:localhost/<unresolved>:8123, db=default)@1838784696

**How to reproduce**

```sql
CREATE EXTERNAL STREAM frontend_events_json(
	version int,
	requestedUrl string,
	method string,
	correlationId string,
	ipAddress string,
	requestDuration int,
	response string,
	headers string
)	
SETTINGS type='kafka', 
         brokers='redpanda:9092',
         topic='owlshop-frontend-events',
         data_format='JSONEachRow';
-- test write JSON
CREATE EXTERNAL STREAM target1(
    _tp_time datetime64(3), 
    url string, 
    method string, 
    ip string) 
    SETTINGS type='kafka', 
             brokers='redpanda:9092', 
             topic='jsonl', 
             data_format='JSONEachRow';
CREATE MATERIALIZED VIEW mv1 INTO target1 AS 
    SELECT now64() AS _tp_time, 
           requestedUrl AS url, 
           method, 
           lower(hex(md5(ipAddress))) AS ip 
    FROM frontend_events_json;
```

**Error message and/or stacktrace**

**Additional context**

**Comment by chenziliang** [comment]
We will need differentiate if it is DDL query or if it s a regular SELECT query. Only for SELECT query, we enforce table behavior.
