### ISSUE TITLE
`select rand(), rand();` will produce the same number.

### ISSUE THREAD

**Issue by leo-cai-timeplus** [timeplus-io/proton#387]
**Describe what's wrong**

run `select rand() as a, rand() as b;`, and `a` will always be equal to `b`, which is not as expected.
we expect that `a` should not always be equal to `b`.
**How to reproduce**
```sql
select rand() as a, rand() as b, a-b as diff;
```
sample result:
```
┌──────────a─┬──────────b─┬─diff─┐
│ 4226338558 │ 4226338558 │    0 │
└────────────┴────────────┴──────┘

┌─────────a─┬─────────b─┬─diff─┐
│ 248777950 │ 248777950 │    0 │
└───────────┴───────────┴──────┘
```

**Comment by chenziliang** [comment]
this is probably a feature, isn't it ?

**Comment by yokofly** [comment]
https://fiddle.clickhouse.com/393b7a18-01de-466b-a6fb-75e26a2efeb7
clickhouse same behaviour

**Comment by leo-cai-timeplus** [comment]
```sql
create random stream rd(
  k1 int default rand()%100,
  k2 int default rand()%100
) settings eps=0;
```
`k1` will always be equal to `k2`

**Comment by leo-cai-timeplus** [comment]
``` sql
select rand(1), rand(2);
```
result:
```
┌───rand(1)─┬─rand(2)─┐
│ 894065041 │ 8816715 │
└───────────┴─────────┘
```

**Comment by lizhou1111** [comment]
If you want to generate two random value during one row, you can `SELECT rand(1), rand(2) - will output two different columns`.

**Comment by jhao0117** [comment]
@leo-cai-timeplus, if this is not a issue, please label it as 'invalid', 'invalid' should be an existing label.
