### ISSUE TITLE
Improve checkpoint versioning stability

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#421]
**Use case**

In proton, query state management is works via checkpoints. currently we use a strict checkpoint/recover implementation, which is easily broken when there are any modifications about query pipeline,  processors or its header changes.

So we want to improve the stability of checkpoints, and reduce broken scenarios as much as possible

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
