### ISSUE TITLE
Streaming processing supports nullable datatype

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#422]
**Use case**

for now, `nullable` type is not be supported in streaming processing, need supports it

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by yl-lisen** [comment]
@lizhou1111 TODO list:
- [x] initial version (#594 )
- [ ] checking more functions
- [ ] add testing

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
Done in last sprint
