### ISSUE TITLE
Base64 decode/decode function

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/proton#427]
base64 encode and decode are very common function when handling string data.

ClickHouse has such support and Proton does not.  https://clickhouse.com/docs/en/sql-reference/functions/string-functions

**Comment by lizhou1111** [comment]
The base64 encode/decode function is also supported by proton, but it is not enable by default.If you build proton with `-DUSE_BASE64=true` flag such as `cmake .. -DUSE_BASE64=true`,you can use these functions then.
```
timeplus-OptiPlex-7000 :) select base64_decode('aaaa')

SELECT
  base64_decode('aaaa')

Query id: 724137bd-fe2d-4a5c-8216-a91c48f762b5

┌─base64_decode('aaaa')─┐
│ i��                     │
└───────────────────────┘

1 row in set. Elapsed: 0.047 sec. 
```

**Comment by jovezhong** [comment]
Let's enable this by default. It won't add too many extra bytes to the binary.

**Comment by lizhou1111** [comment]
done in https://github.com/timeplus-io/proton/pull/444

**Comment by jovezhong** [comment]
Reopened this, since only base58_encode/etc are available

```
select base64_encode('aa')

SELECT
  base64_encode('aa')

Query id: 10717426-e33b-48d3-961a-b5670cd32f44


0 rows in set. Elapsed: 0.024 sec. 

Received exception from server (version 1.3.29):
Code: 46. DB::Exception: Received from localhost:8463. DB::Exception: Unknown function base64_encode. Maybe you meant: ['base58_encode','base58_decode']. (UNKNOWN_FUNCTION
```

CC @gangtao

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
