### ISSUE TITLE
Support ML function with streaming inference

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/proton#430]
refer to ClickHouse ML functions https://clickhouse.com/docs/en/sql-reference/functions/machine-learning-functions

it is better to support

1. train the model with historical data
2. inferece using the trained model in streaming mode.

related document is desired as well.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
