### ISSUE TITLE
The behavior of External Stream with nullable datatype need to be discussed.

### ISSUE THREAD

**Issue by lizhou1111** [timeplus-io/proton#432]
If you create a external stream with nullable data type, like below.
```sql
drop stream if exists test1;
create external stream if not exists test1(
	int8_col nullable(int8),
	uuid_col nullable(uuid),
	ipv4_col nullable(ipv4)
	) settings type = 'kafka', brokers = 'redpanda-1:9092', topic = 'test', data_format='JSONEachRow';
```
The user data may lack some fileds such as the `IPV4` address. So there are three situations for kafka messages sent by users:
1. `{"int8_col":1,"uuid_col":"928c88b9-f37a-41d5-bef5-9cb3663c2445"}`.There is just no such field, it's ok,Proton will read `Null` value and can parse this piece of message.
2. `{"int8_col":1,"uuid_col":"928c88b9-f37a-41d5-bef5-9cb3663c2446", "ipv4_col":null}`. Insert `Null` value explicitly, it's also ok.Ptoton will read ​`Null` value successfully.
3. `{"int8_col":1,"uuid_col":"928c88b9-f37a-41d5-bef5-9cb3663c2447", "ipv4_col":""}`. Insert empty string,this piece of data will lose.Because it will handle as exception in the `readIPv4TextImpl` function.The handling of this situation is different. The specific behavior depends on the data type.Some data type will have value, such as `{"int8_col":"","uuid_col":"928c88b9-f37a-41d5-bef5-9cb3663c2448", "ipv4_col":"192.168.0.1"}`,you will get `0` value, the other data type will throw exception that means you will lose this piece of data.The read method implementation of each data type is different.

Below is the output:
```
timeplus-OptiPlex-7000 :) select * from test1

SELECT
  *
FROM
  test1

Query id: b421e811-a39f-442a-a17f-3f5f74e5f35f

┌─int8_col─┬─uuid_col─────────────────────────────┬─ipv4_col─┐
│        1 │ 928c88b9-f37a-41d5-bef5-9cb3663c2445 │ ᴺᵁᴸᴸ     │
└──────────┴──────────────────────────────────────┴──────────┘
┌─int8_col─┬─uuid_col─────────────────────────────┬─ipv4_col─┐
│        1 │ 928c88b9-f37a-41d5-bef5-9cb3663c2446 │ ᴺᵁᴸᴸ     │
└──────────┴──────────────────────────────────────┴──────────┘
┌─int8_col─┬─uuid_col─────────────────────────────┬─ipv4_col─┐
│        0 │ 928c88b9-f37a-41d5-bef5-9cb3663c2448 │ ᴺᵁᴸᴸ     │
└──────────┴──────────────────────────────────────┴──────────┘
```

The main point is if the data type is Nullable and parsing fails, should a Null value be returned instead of discarding the data?

**Comment by zliang-min** [comment]
IMO, parsing failures do not equal to Null. This should be discussed case by case, maybe in some cases, we want to enhacne how some values should be parsed/converted to some specific types.
