### ISSUE TITLE
Support message keys for Kafka external stream

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#433]
**Use case**

As a kafka external streams user, I would like to be able to set the message keys on messages which are sent to a Kafka external stream.

**Describe the solution you'd like**

Add a `message_key` external stream setting to specify an expression for generating message keys. E.g.

```sql
CREATE EXTERNAL STREAM example (
  field_one string,
  field_two int32,
  ...
) SETTINGS type='kafka',...,message_key='field_one';
```

`message_key` can be any expression that returns a string value (string or fixedstring):

```sql
CREATE EXTERNAL STREAM example (
  field_one string,
  field_two int32,
  ...
) SETTINGS type='kafka',...,message_key='split_by_string(\',\', field_one)[1]';
```

**Describe alternatives you've considered**

There is already a setting `sharding_expr` which allows to specify a function expression to calculate the partition ID of messages, however, message keys could be more useful than just for partitioning, also, they are also part of the messages' metadata stored in Kafka brokers.

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
