### ISSUE TITLE
Write to Kafka external stream with raw data format should only send the raw data to Kafka

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#435]
**Describe what enhancement you'd like to have**

Currently, when `data_format` is not speicified in `CREATE EXTERNAL STREAM` with `type='kafka'` and there is only one string value column, it uses the Raw data format.

When reading from such a stream, the behavior is correct, it uses the message payload as-is as the column value. However, when writing to such a stream, it writes a JSON object, something like `{"data": "<the-raw-value>"}`. This is not the correct raw format behavior, this is exactly the same as using `JSONEachRow` format. The correct behavior for raw writing is to just write the string value as the Kafka message payload without adding any other thing to it. Simply put with the following SQL:

```sql
INSERT INTO my_raw_kafka_external_stream SELECT FROM my_raw_kafka_external_stream
```

should keep producing the unique message again and again to the Kafka topic.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
