### ISSUE TITLE
Support tracking whether the aggregation window or group is changed

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#446]
**Use case**

Choose a good way to track whether the aggregation window or group changes, which can be used in:
- emit changelog for aggregated result (supported, but there are some bugs)
- only emit changed windows (TODO)
- only emit changed groups (TODO)
- incremental checkpointing (TODO)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
