### ISSUE TITLE
Kafka External Stream: support SCRAM-SHA-256 and  SCRAM-SHA-512

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#453]
**Describe what enhancement you'd like to have**

Currently, Kafka external streams only support one SASL mechnism `PLAIN`, in order to be able to connect to more Kafka deployments, we should also support SCRAM-SHA-256 and  SCRAM-SHA-512.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
