### ISSUE TITLE
CREATE MATERIALIZED VIEW Failed for streaming query

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#498]
**Describe what's wrong**

```sql
create stream dim_t(id int, type int);
create stream vk(id int, value float) primary key id settings mode='versioned_kv';
create materialized view mv as with list as (select id from table(dim_t)) select id, value from vk where id in list;
```
**But got exception:**
Received exception from server (version 1.3.31):
Code: 48. DB::Exception: Received from localhost:8463. DB::Exception: SUBSCRIBE can only work with streaming query. (NOT_IMPLEMENTED)

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
