### ISSUE TITLE
Expose extract_key_value_pairs function

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#522]
ClickHouse supports `SELECT extractKeyValuePairs('name:neymar, age:31 team:psg,nationality:brazil') as kv` https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions#extractkeyvaluepairs

This is mentioned in our of our community user. Current this is not available in Proton

Unknown function extract_key_value_pairs. (UNKNOWN_FUNCTION) (version 1.3.31).

**Comment by yokofly** [comment]
this function is not suitable for JSON, `json_extract_keys_and_values_raw` shall be more specific.

**Comment by jovezhong** [comment]
Hi @yokofly 

`select json_extract_keys_and_values_raw('{"a":1,"b":2}')` works and return an array.
However, the user expects to get a map, to easily access key/value pairs.

If we run `extract_key_value_pairs('"a":1,"b":2')` this can return a map with a and b as key

**Comment by yokofly** [comment]
okay, if we care about the output I think this is reasonable 
https://play.clickhouse.com/play?user=play#d2l0aCBjdGUgYXMgKAogICAgc2VsZWN0ICd7XCJuYW1lXCI6XCJKYW5lXCIsXCJkYXRlXCI6XCJNYXkyNFwifScgYXMgcmF3CikgCnNlbGVjdCAKICAgIGFycmF5Sm9pbihleHRyYWN0S2V5VmFsdWVQYWlycyhyYXcpKSBhcyBrdl9wYWlyLAogICAgdG9UeXBlTmFtZShleHRyYWN0S2V5VmFsdWVQYWlycyhyYXcpKSwKICAgIGFycmF5Sm9pbihKU09ORXh0cmFjdEtleXNBbmRWYWx1ZXNSYXcocmF3KSkgYXMga3ZfcGFpcl9mcm9tX2pzb24sCiAgICB0b1R5cGVOYW1lKEpTT05FeHRyYWN0S2V5c0FuZFZhbHVlc1JhdyhyYXcpKQpmcm9tIGN0ZTsK
