### ISSUE TITLE
incorrect 'trim' function after formatted

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#523]
**Describe what's wrong**

**How to reproduce**
```bash
formatted_sql=`proton format --query "select trim(BOTH '\"' from '"test"') == 'test'"`; proton client --query "$formatted_sql"
```

`Code: 62. DB::Exception: Syntax error: failed at position 21 (',') (line 2, col 14): , concat('^[', regexp_quote_meta('"'), ']*|[', regexp_quote_meta('"'), ']*$'), '') = 'test'. Expected one of: NOT, BETWEEN, IS, end of query. (SYNTAX_ERROR)`

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
