### ISSUE TITLE
[External Stream] Format settings declared on creation time should be taken into account

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#533]
**Use case**

Currently, format settings can be declared on creation time when create a external stream, for example:

```sql
create or replace external stream users (
           user_id uint32,
           message string,
           timestamp datetime,
           metric float32
           ) settings type='kafka',
           topic='src',
           brokers='localhost:9092',
           data_format='JSONEachRow',
           input_format_skip_unknown_fields=true;
```

The above code uses ` input_format_skip_unknown_fields=true` and expects `SELECT` queries will ignore unknow fileds. However this does not work. One has to specify the setting in the `SELECT` queries like:

```sql
SELECT * FROM users SETTINGS  input_format_skip_unknown_fields=true
```

This is troublesome, because such settings likely should be applied to every `SELECT` queries against that stream.

**Describe the solution you'd like**

The format settings declared on creation time should be taken into account.

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
