### ISSUE TITLE
SUSE Linux build error

### ISSUE THREAD

**Issue by Shylock-Hg** [timeplus-io/proton#540]
I try to build this project following `build.md`, but this failed as:
```
[20/3905] Building CXX object contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/builtins/setup-builtins-internal.cc.o
FAILED: contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/builtins/setup-builtins-internal.cc.o 
/usr/bin/ccache /usr/bin/clang++ --target=x86_64-linux-gnu --sysroot=/home/shylock/Workspace/proton/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DHAS_RESERVED_IDENTIFIER -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DV8_CONCURRENT_MARKING -DV8_HAVE_TARGET_OS -DV8_TARGET_ARCH_X64 -DV8_TARGET_OS_LINUX -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/home/shylock/Workspace/proton/contrib/v8-cmake/v8/include -I/home/shylock/Workspace/proton/build/contrib/v8-cmake/generated -I/home/shylock/Workspace/proton/contrib/v8-cmake/v8 -I/home/shylock/Workspace/proton/contrib/v8-cmake/v8/third_party/zlib -I/home/shylock/Workspace/proton/build/contrib/v8-cmake -I/home/shylock/Workspace/proton/base/glibc-compatibility/memcpy -isystem /home/shylock/Workspace/proton/contrib/llvm-project/libcxx/include -isystem /home/shylock/Workspace/proton/contrib/llvm-project/libcxxabi/include -isystem /home/shylock/Workspace/proton/contrib/libunwind/include --gcc-toolchain=/home/shylock/Workspace/proton/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/shylock/Workspace/proton=. -falign-functions=32 -mbranches-within-32B-boundaries   -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie -std=gnu++23   -D OS_LINUX -DV8_ENABLE_WEBASSEMBLY -DV8_ADVANCED_BIGINT_ALGORITHMS -DV8_ENABLE_WASM_SIMD256_REVEC -fno-exceptions -Wno-invalid-offsetof -Wno-deprecated-non-prototype -Werror -nostdinc++ -MD -MT contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/builtins/setup-builtins-internal.cc.o -MF contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/builtins/setup-builtins-internal.cc.o.d -o contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/builtins/setup-builtins-internal.cc.o -c /home/shylock/Workspace/proton/contrib/v8-cmake/v8/src/builtins/setup-builtins-internal.cc
[29/3905] Building CXX object contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/extensions/externalize-string-extension.cc.o
ninja: build stopped: subcommand failed.
```
 The build command for one object failed, but this don't display the compile error message, and as I known, ninja will display `command`, `stdout` and `stderr` by default when command failed.

**Comment by qijun-niu-timeplus** [comment]
Thank you for attempting to build Proton. To better assist you, could you please provide us with more details about your compilation environment? This information will help us identify the root cause of the problem and provide a more accurate solution.

What's your CPU Architecture, ARM or x86?
What is the version of your operating system?
Did you use Docker or bare-metal (host machine) for building Proton?
If using bare-metal, could you please provide the CMake options you used.

These details will greatly assist us in replicating and diagnosing the compilation issue.

**Comment by Shylock-Hg** [comment]
> Thank you for attempting to build Proton. To better assist you, could you please provide us with more details about your compilation environment? This information will help us identify the root cause of the problem and provide a more accurate solution.
> 
> What's your CPU Architecture, ARM or x86? What is the version of your operating system? Did you use Docker or bare-metal (host machine) for building Proton? If using bare-metal, could you please provide the CMake options you used.
> 
> These details will greatly assist us in replicating and diagnosing the compilation issue.

1. x86
2. WSL/OpenSUSE  tumbleweed
3. host machine
4. I just use raw `cmake ..`

**Comment by yokofly** [comment]
thanks for the reply. the OpenSuse we do not fully test I guess.
Building proton really costs time(hahaha), but installing the env/dependency is more complex.

would you like to use docker build? this shall not affected by the env. 

Regarding your problem about `Ninja does not display the msg`, I have no idea.
but months ago I built the proton and also hit the same issue with v8 and Ninja failed without any useful log.
I will take a look this build error.

**Comment by Shylock-Hg** [comment]
```
[458665.635709] Out of memory: Killed process 20089 (clang++) total-vm:7213128kB, anon-rss:6946328kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:14104kB oom_score_adj:0
```
I rerun the command manually, and found it's caused by OOM.

**Comment by jovezhong** [comment]
Hi @Shylock-Hg , you closed the ticket. Does it mean you have successfully built the project?

**Comment by Shylock-Hg** [comment]
> Hi @Shylock-Hg , you closed the ticket. Does it mean you have successfully built the project?

No, I meet some compile warning as :
```
/home/shylock/Workspace/proton/src/Interpreters/threadPoolCallbackRunner.h:20:13: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
```
My compiler is 
```
clang version 17.0.6
Target: x86_64-suse-linux
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-suse-linux/13
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-suse-linux/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

With default compile options by `cmake ..`.

**Comment by jovezhong** [comment]
Let me reopen this ticket then, and add SUSE Linux in the title.  Our dev team and CI are not SUSE Linux, so the build process on SUSE is not verified and could be improved. We will take a look later. In the meanwhile, if you find anything can be improved, feel free to send us a PR

**Comment by yokofly** [comment]
this is expected, we still support and test on clang16, upgrade to clang17 will be deferred to China new year. 

I recalled using clang17 compile proton just needed to solve some warnings. but proton default turn  **warn-as-error** 


@Shylock-Hg we are welcome for new PR to fix the warning on clang17 if you have time on this trial. 
tips: check clickhouse current code line if you are not sure how to fix it.

**Comment by Shylock-Hg** [comment]
> @Shylock-Hg  check clickhouse current code line if you are not sure how to fix it.

Can you detail this?

**Comment by yokofly** [comment]
> > @Shylock-Hg  check clickhouse current code line if you are not sure how to fix it.
> 
> Can you detail this?

The warning is because a higher version clang compiler will enable more kinds of warn checks.
and clickhouse has migrated to clang-17, proton still in clang-16. and the proton is fork from clickhouse.
if the warning is hard to fix, we can search the code line to check how the clickhouse solves the warning.

about the above post warning, I assume below maybe fix it?

https://github.com/ClickHouse/ClickHouse/commit/5a44dc26e7048e7e2752cc87897157301fb1e278#diff-64e557fae616787dd9a2b9993b0d273ef80cea55fa1febacd3d99dfc9a21d476R20-R24

**Comment by Shylock-Hg** [comment]
> > > @Shylock-Hg  check clickhouse current code line if you are not sure how to fix it.
> > 
> > 
> > Can you detail this?
> 
> The warning is because a higher version clang compiler will enable more kinds of warn checks. and clickhouse has migrated to clang-17, proton still in clang-16. and the proton is fork from clickhouse. if the warning is hard to fix, we can search the code line to check how the clickhouse solves the warning.
> 
> about the above post warning, I assume below maybe fix it?
> 
> [ClickHouse/ClickHouse@5a44dc2#diff-64e557fae616787dd9a2b9993b0d273ef80cea55fa1febacd3d99dfc9a21d476R20-R24](https://github.com/ClickHouse/ClickHouse/commit/5a44dc26e7048e7e2752cc87897157301fb1e278#diff-64e557fae616787dd9a2b9993b0d273ef80cea55fa1febacd3d99dfc9a21d476R20-R24)

Ok, I will follow this to rename shadowed variables.

**Comment by yokofly** [comment]
> > > > @Shylock-Hg  check clickhouse current code line if you are not sure how to fix it.
> > > 
> > > 
> > > Can you detail this?
> > 
> > 
> > The warning is because a higher version clang compiler will enable more kinds of warn checks. and clickhouse has migrated to clang-17, proton still in clang-16. and the proton is fork from clickhouse. if the warning is hard to fix, we can search the code line to check how the clickhouse solves the warning.
> > about the above post warning, I assume below maybe fix it?
> > [ClickHouse/ClickHouse@5a44dc2#diff-64e557fae616787dd9a2b9993b0d273ef80cea55fa1febacd3d99dfc9a21d476R20-R24](https://github.com/ClickHouse/ClickHouse/commit/5a44dc26e7048e7e2752cc87897157301fb1e278#diff-64e557fae616787dd9a2b9993b0d273ef80cea55fa1febacd3d99dfc9a21d476R20-R24)
> 
> Ok, I will follow this to rename shadowed variables.

this is not urgent, do not worry if you have no time to handle this task.
