### ISSUE TITLE
[External Stream] set input_format_skip_unknown_fields default to true

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#549]
**Describe what enhancement you'd like to have**

When using external streams to ingest data (in JSON format), people easily encounter the unknown fields error which causes the data won't be return as the query results. This could easily confuse people if they don't know about the `input_format_skip_unknown_fields` setting and do not check logs. Changing the default value of that setting to true for external streams will make things easier.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
