### ISSUE TITLE
`comment` doesn't work for `create external stream`

### ISSUE THREAD

**Issue by ye11ow** [timeplus-io/proton#563]
**Describe what's wrong**

When creating external stream, `comment` option doesn't work. It works for normal stream though.

**How to reproduce**

* `create external stream ext_helloworld (raw string) settings type = 'kafka', brokers = 'X', topic = 'X', security_protocol = 'SASL_SSL', username = 'X', password = 'X' comment 'test'`
* `select * from system.tables where database ='default' and engine='ExternalStream' FORMAT Vertical`

```
──────
database:                      default
name:                          ext_helloworld
uuid:                          ce87f9df-0df4-435e-beb3-67ad1e64db00
engine:                        ExternalStream
...
create_table_query:            CREATE STREAM default.ext_helloworld
(`raw` string
)
ENGINE = ExternalStream()
SETTINGS type = 'kafka', brokers = 'X', topic = 'X', security_protocol = 'X', username = 'X', password = 'X'
COMMENT 'test'
engine_full:
ENGINE = ExternalStream()
SETTINGS type = 'kafka', brokers = 'X', topic = 'github_events', security_protocol = 'SASL_SSL', username = 'X', password = 'X'
mode:
...
comment:
...
```

Noticed that the `comment` field is empty.
Also why there are two `SETTINGS` and `ENGINE` in `create_table_query` field? The issues seem to be related?

**Error message and/or stacktrace**

**Additional context**

**Comment by chenziliang** [comment]
Probably AST layer parser didn't handle comment

**Comment by zliang-min** [comment]
I checked the code, the parser is good, and the AST is correct. The comment somehow is not stored in the `tables` table, need to dig deeper to figure out why.

For @ye11ow 's question:
> Also why there are two SETTINGS and ENGINE in create_table_query field? The issues seem to be related?

There are not. There is another field called `engine_full`, I think you missed that.
