### ISSUE TITLE
insert 1707954127790 to a `float` column will get `1707954100000`

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#564]
**Describe what's wrong**

This is reported by a community user.
There is a column in the stream in `float` or `float32` type.
When the value `1707954127790` is inserted, then query the stream, the value is shown as `1707954100000`

The workaround is to declare the column as `int64`, which is `long`
But wondering the reason for current behavior. 

Proton 1.4.2

**Comment by chenziliang** [comment]
you will need use a double or float64 ?

**Comment by jovezhong** [comment]
Close the issue, since this is more like a limitation of float32. Same behavior in ClickHouse.

In this concrete use case, 1707954127790 is saved for timestamp with millisecond. If it's a JSON without schema, we should save it as int64 (i.e. long). If the user can apply a Avro/etc schema, should use `long` and our UI/workflow should respect this type.
