### ISSUE TITLE
failed to trigger checkpointing state error dir already exists

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#589]
**Describe what's wrong**

a lot of follow errors
```
<Error> CheckpointCoordinator: Failed to trigger checkpointing state for query=.mv-47ad3091-8e3e-49d7-ad31-071b7b13b3e9 epoch=74 error=Directory '/var/lib/proton/checkpoint/.mv-47ad3091-8e3e-49d7-ad31-071b7b13b3e9/74' already exists.
```
<img width="1752" alt="image" src="https://github.com/timeplus-io/proton-enterprise/assets/38773813/d6041afa-675b-453b-af2f-b8e868437ef0">

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
