### ISSUE TITLE
improve the fault tolerance of materialized view

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#590]
**Describe what enhancement you'd like to have**
When send dirty data to proton (for example, an integer to a float32 column)
it will cause the mv failed with exception

proton will try to recover the fail mv forever. But due to the dirty data, it cannot recover successfully.

Expected Result:
proton can log the dirty data which cause the failure
when recover mv, proton can skip the dirty and recover the mv successfully.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
