### ISSUE TITLE
versioned_kv support max_k

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#6]
**Use case**
```cpp
// src/Interpreters/Streaming/SubstituteStreamingFunction.cpp:56
std::unordered_map<String, String> StreamingFunctionData::changelog_func_map = {
    {"count", "__count_retract"},
    {"sum", "__sum_retract"},
    {"sum_kahan", "__sum_kahan_retract"},
    {"sum_with_overflow", "__sum_with_overflow_retract"},
    {"avg", "__avg_retract"},
    {"max", "__max_retract"},
    {"min", "__min_retract"},
    {"arg_min", "__arg_min_retract"},
    {"arg_max", "__arg_max_retract"},
    {"latest", ""},
    {"earliest", ""},
    {"first_value", ""},
    {"last_value", ""},
    {"top_k", ""},
    {"min_k", ""},
    {"max_k", ""},
...
};
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yokofly** [comment]
expected `count_if()` instead `__count_retract_if`
update v1: This has been fixed in https://github.com/timeplus-io/proton/commit/23a1871f1fe886cf4aece4e59611a9fc0d84ca57#diff-bc7774e904912e097c24c8edbc7765ade28e37496c3837905f33e61b583b09cbR94

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
