### ISSUE TITLE
setting emit_aggregated_during_backfill does not exist

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/proton#600]
According to the doc https://docs.timeplus.com/query-syntax#settings , there is a setting `emit_aggregated_during_backfill ` 

While , in latest proton 1.5.3, there is no such setting.

In case there is no such setting, how to enable emit during backfill?

here is the error

```
SELECT 
  window_start, count(*) AS count, hash, geohash_decode(hash) AS hash_decode, hash_decode.1 AS long, hash_decode.2 AS lat
FROM 
  tumble(v_flows_source_locations, 1s)
WHERE 
  _tp_time > (now() - 2m)
GROUP BY 
  window_start, hash
settings seek_to = '-2m', emit_aggregated_during_backfill=1


Code: 115. DB::Exception: Unknown setting emit_aggregated_during_backfill. (UNKNOWN_SETTING) (version 1.5.3)
```

**Comment by yl-lisen** [comment]
the doc `emit_aggregated_during_backfill` is outdate, current is `emit_during_backfill`:
` M(Bool, emit_during_backfill, false, "Enable emit intermediate aggr result during backfill historical data", 0) \`

@jovezhong  needs to revisit it

**Comment by jovezhong** [comment]
Thanks, I updated the doc via https://github.com/timeplus-io/docs/commit/7b7e85a1e7db67a190af8f74a59adf292e8900b9

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
