### ISSUE TITLE
Proton external stream to support Debezium CDC message in Avro schema

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#610]
Since Proton 1.5.2, Kafka schema registry is supported. Then we should start improving the Debezium integration.

Currently if you configure Debezium to generate JSON messages without Avro or Protobuf, Proton can read them and process them. Please check the example at https://github.com/timeplus-io/proton/tree/develop/examples/cdc

However, if Avro format is turned on with a confluent (compatible) schema registry, not all fields can be read.

# What is working
`op` is a string field and always exists in all messages. If you create the external steam, only with `op` field, it's working
```sql
CREATE EXTERNAL STREAM customers_avro(op string)
SETTINGS 	type='kafka',
          brokers='redpanda:9092',
          topic='dbserver1.inventory.customers',
          data_format='Avro',
          kafka_schema_registry_url='http://redpanda:8081';
```
Run `select * from customers_avro where _tp_time>earliest_ts()` you will get
```
┌─op─┐
│ r  │
│ r  │
│ r  │
│ r  │
└────┘
```

# Avro Schema

The full Avro schema for the value is
```json
{
  "type": "record",
  "name": "Envelope",
  "namespace": "dbserver1.inventory.customers",
  "fields": [
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Value",
          "fields": [
            { "name": "id", "type": "int" },
            { "name": "first_name", "type": "string" },
            { "name": "last_name", "type": "string" },
            { "name": "email", "type": "string" }
          ],
          "connect.name": "dbserver1.inventory.customers.Value"
        }
      ],
      "default": null
    },
    { "name": "after", "type": ["null", "Value"], "default": null },
    {
      "name": "source",
      "type": {
        "type": "record",
        "name": "Source",
        "namespace": "io.debezium.connector.mysql",
        "fields": [
          { "name": "version", "type": "string" },
          { "name": "connector", "type": "string" },
          { "name": "name", "type": "string" },
          { "name": "ts_ms", "type": "long" },
          {
            "name": "snapshot",
            "type": [
              {
                "type": "string",
                "connect.version": 1,
                "connect.parameters": {
                  "allowed": "true,last,false,incremental"
                },
                "connect.default": "false",
                "connect.name": "io.debezium.data.Enum"
              },
              "null"
            ],
            "default": "false"
          },
          { "name": "db", "type": "string" },
          { "name": "sequence", "type": ["null", "string"], "default": null },
          { "name": "table", "type": ["null", "string"], "default": null },
          { "name": "server_id", "type": "long" },
          { "name": "gtid", "type": ["null", "string"], "default": null },
          { "name": "file", "type": "string" },
          { "name": "pos", "type": "long" },
          { "name": "row", "type": "int" },
          { "name": "thread", "type": ["null", "long"], "default": null },
          { "name": "query", "type": ["null", "string"], "default": null }
        ],
        "connect.name": "io.debezium.connector.mysql.Source"
      }
    },
    { "name": "op", "type": "string" },
    { "name": "ts_ms", "type": ["null", "long"], "default": null },
    {
      "name": "transaction",
      "type": [
        "null",
        {
          "type": "record",
          "name": "block",
          "namespace": "event",
          "fields": [
            { "name": "id", "type": "string" },
            { "name": "total_order", "type": "long" },
            { "name": "data_collection_order", "type": "long" }
          ],
          "connect.version": 1,
          "connect.name": "event.block"
        }
      ],
      "default": null
    }
  ],
  "connect.version": 1,
  "connect.name": "dbserver1.inventory.customers.Envelope"
}

```

# Sample value in the customers topic
```json
{
    "after": {
        "dbserver1.inventory.customers.Value": {
            "email": "annek@noanswer.org",
            "first_name": "Anne",
            "id": 1004,
            "last_name": "Kretchmar"
        }
    },
    "before": null,
    "op": "r",
    "source": {
        "connector": "mysql",
        "db": "inventory",
        "file": "mysql-bin.000003",
        "gtid": null,
        "name": "dbserver1",
        "pos": 157,
        "query": null,
        "row": 0,
        "sequence": null,
        "server_id": 0,
        "snapshot": {
            "string": "last_in_data_collection"
        },
        "table": {
            "string": "customers"
        },
        "thread": null,
        "ts_ms": 1710631967000,
        "version": "2.5.0.Final"
    },
    "transaction": null,
    "ts_ms": {
        "long": 1710631967915
    }
}
```

# What is not working

Let's try to get the `ts_ms` field
> { "name": "ts_ms", "type": ["null", "long"], "default": null },

Sample message is
> "ts_ms": {
>         "long": 1710631967915
>     }

SQL
```sql
CREATE EXTERNAL STREAM customers_avro2(op string, ts_ms tuple(long int64))
SETTINGS type='kafka',
brokers='redpanda:9092',
topic='dbserver1.inventory.customers',
data_format='Avro',
kafka_schema_registry_url='http://redpanda:8081';
```
Nothing shown in the SQL client

`tail /var/log/proton-server/proton-server.log`

> 2024.03.17 00:34:44.346018 [ 349 ] {f0d7f343-0a39-4af7-9b28-445fb4b4aafe} <Error> External-dbserver1.inventory.customers: Failed to parse message at 3: Type tuple(long int64) is not compatible with Avro union:
> [
>     "null",
>     "long"
> ]: column ts_ms

Maybe there is a better way to map the Avro union.

The `after` field is `"type": ["null","Value" ]`, while the `Value` is defined in `before`
```json
        {
          "type": "record",
          "name": "Value",
          "fields": [
            {
              "name": "id",
              "type": "int"
            },
            {
              "name": "first_name",
              "type": "string"
            },
            {
              "name": "last_name",
              "type": "string"
            },
            {
              "name": "email",
              "type": "string"
            }
          ],
          "connect.name": "dbserver1.inventory.customers.Value"
        }
```

**Comment by jovezhong** [comment]
Doing a bit more research. The annoying part of Avro is that union object can be wrapped. For example `"type": ["null", "long"]`, this could be just `"ts_ms":null` or `"ts_ms": 1710631967915 ` . But the default encoder will generate `"ts_ms": {"long": 1710631967915}` The issue has been reported **10** years ago. Some people created custom encoder/decoder but this remains the default behavior

https://issues.apache.org/jira/browse/AVRO-3210
https://issues.apache.org/jira/browse/AVRO-1582

The other thing we at Proton team should look into is how to retrieve the `after` field with data_format=Avro
```json
    "after": {
        "dbserver1.inventory.customers.Value": {
            "email": "annek@noanswer.org",
            "first_name": "Anne",
            "id": 1004,
            "last_name": "Kretchmar"
        }
    },
```

**Comment by jovezhong** [comment]
I found a workaround to simply the Avro message, so that Proton can read all columns without worrying about nullable or complex data structure, by following the doc at https://debezium.io/documentation/reference/stable/transformations/event-flattening.html 

The key change is add transforms=unwarp while creating the Debezium job
```json
"transforms": "unwrap",
"transforms.unwrap.type":"io.debezium.transforms.ExtractNewRecordState",
"transforms.unwrap.drop.tombstones":"false",
"transforms.unwrap.delete.handling.mode":"rewrite",
"transforms.unwrap.add.fields":"table,lsn",
```

Then the schema will turn to
```json
{
  "type": "record",
  "name": "Value",
  "namespace": "dbserver1.inventory.customers",
  "fields":
    [
      { "name": "id", "type": "int" },
      { "name": "first_name", "type": "string" },
      { "name": "last_name", "type": "string" },
      { "name": "email", "type": "string" },
      { "name": "__deleted", "type": ["null", "string"], "default": null },
      { "name": "__table", "type": ["null", "string"], "default": null },
    ],
  "connect.name": "dbserver1.inventory.customers.Value",
}
```

then sample message will be
```json
{
  "__deleted": {
      "string": "false"
  },
  "__table": {
      "string": "customers"
  },
  "email": "annek@noanswer.org",
  "first_name": "Anne",
  "id": 1004,
  "last_name": "Kretchmar"
}
```

So you can just create an external stream via
```sql
CREATE EXTERNAL STREAM customers_avro(
  id int,
  first_name string,
  last_name string,
  email string
)
SETTINGS type='kafka',
          brokers='redpanda:9092',
          topic='dbserver1.inventory.customers',
          data_format='Avro',
          kafka_schema_registry_url='http://redpanda:8081';
```
Then query it via `select * from customers_avro where _tp_time>earliest_ts();`
Get result
```
┌───id─┬─first_name─┬─last_name─┬─email─────────────────┐
│ 1001 │ Sally      │ Thomas    │ sally.thomas@acme.com │
│ 1002 │ George     │ Bailey    │ gbailey@foobar.com    │
│ 1003 │ Edward     │ Walker    │ ed@walker.com         │
│ 1004 │ Anne       │ Kretchmar │ annek@noanswer.org    │
└──────┴────────────┴───────────┴───────────────────────┘
```

**Comment by zliang-min** [comment]
Need to port the enhancements from CH to our repo:
* Our code: https://github.com/timeplus-io/proton/blob/develop/src/Processors/Formats/Impl/AvroRowInputFormat.cpp#L399
* CH's code: https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Formats/Impl/AvroRowInputFormat.cpp#L554

**Comment by zliang-min** [comment]
Just read this issue carefully, so for this part:

> Let's try to get the ts_ms field
> 
> { "name": "ts_ms", "type": ["null", "long"], "default": null },
> 
> Sample message is
> 
> "ts_ms": {
> "long": 1710631967915
> }
> 
> SQL
> 
> CREATE EXTERNAL STREAM customers_avro2(op string, ts_ms tuple(long int64))
> SETTINGS type='kafka',
> brokers='redpanda:9092',
> topic='dbserver1.inventory.customers',
> data_format='Avro',
> kafka_schema_registry_url='http://redpanda:8081';

This is wrong. the type for `ts_ms` should be `nullable(int64)`, it's not a `tuple`. You should check the schema itself to determine the types of the fields, not the value itself.

**Comment by jovezhong** [comment]
Hi Gimi, I guess you refer to the 1st comment.

Check the 2nd comment
> The annoying part of Avro is that union object can be wrapped. For example "type": ["null", "long"], this could be just "ts_ms":null or "ts_ms": 1710631967915  . But the default encoder will generate "ts_ms": {"long": 1710631967915} 

If we don't apply `io.debezium.transforms.ExtractNewRecordState` transformation, just reading the raw JSON to external stream, the ts_ms is a complex type, i.e. tuple, not a `nullable(long)`

**Comment by zliang-min** [comment]
> Hi Gimi, I guess you refer to the 1st comment.
> 
> Check the 2nd comment
> 
> > The annoying part of Avro is that union object can be wrapped. For example "type": ["null", "long"], this could be just "ts_ms":null or "ts_ms": 1710631967915  . But the default encoder will generate "ts_ms": {"long": 1710631967915}
> 
> If we don't apply `io.debezium.transforms.ExtractNewRecordState` transformation, just reading the raw JSON to external stream, the ts_ms is a complex type, i.e. tuple, not a `nullable(long)`

No, that's wrong. That's why I said "You should check the schema itself to determine the types of the fields, not the value itself.". It generates the message `"ts_ms": {"long": 1710631967915}` is totally fine, but it does not change the type of the `ts_ms` field. Please read the schema:
```json
 { "name": "ts_ms", "type": ["null", "long"], "default": null }
```
`ts_ms` has the type of `optional long`, it's not a `record`, you should not use `tuple`.

**Comment by jovezhong** [comment]
I see where you came from.

sure, to analyze the data,, ts_ms should be an optional long, `nullable(long)`
the JSON payload we got is "ts_ms": {"long": 1710631967915}. In my comment, if we want to parse the JSON directly, one solution is to treat the ts_ms as tuple, then get the nested long. This is just like `raw string`, as a temp solution to access certain data.

In the end, we do need to get a long type or even datetime64 type of ts_ms
