### ISSUE TITLE
External stream still gets created if sasl_mechanism is wrong

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#617]
**Describe what's wrong**

@ye11ow reported in Slack:

> I’m trying to create an ext stream with wrong sasl type
> ```
> CREATE EXTERNAL STREAM ext_calvin_test(raw string)  
> SETTINGS type='kafka',  
> brokers='pkc-ld537.ca-central-1.aws.confluent.cloud:9092',  
> topic='calvin_test',  
> security_protocol='SASL_SSL',  
> sasl_mechanism='SCRAM-SHA-512',  <- This is wrong so the ext stream should not work
> username='YYY',  
> password='XXX'
> ```
> What I expect is that the creation will fail. However, I was able to create the ext stream

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
