### ISSUE TITLE
Queries on ClickHouse external tables with special table names fail

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#623]
**Describe what's wrong**

Reported by a community user, and I quoted here:

> Hello everyone, I was testing proton with a clickhouse external table but I am unable to properly escape some characters in the table name
> I have a clickhouse table like this: prefix_{UUID}
> for example: `prefix_481a213-0186-460a-98f5-60a954bc0712`
> Normally I am able to query this table from clickhouse like `db.`tablename``
> I am however unable to query this table as an external table from proton.
> My external table definition looks like this
> `CREATE EXTERNAL TABLE test SETTINGS type='clickhouse',address='addr',user='admin',password='pass',secure=false,table='prefix_0481a213-0186-460a-98f5-60a954bc0712',database='db'; `
> I can however run describe on it with success: `describe test`
> It seems that I need to do something to escape - character in the table name but I was not able to figure out a solution.

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
