### ISSUE TITLE
Default retention policy for streams: 1d for streaming storage and forever for historical storage

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#632]
**Describe what enhancement you'd like to have**
When the user creates a stream in Timeplus UI, we set 1day for the streaming storage (not configurable) and by default 30 days for historical storage. But if it's CSV upload, by default 'Do not remove' for historical storage, in case very old data in the imported data.

When creating stream via SQL in Proton, or in Timeplus SQL Console, we should apply the same default value. Otherwise the user can easily accumulate a lot of data in the stream storage, and don't know how to set the streaming storage retention (I didn't document this on purpose)

**Comment by yokofly** [comment]
@jovezhong , is this issue considered as backward incompatible?

**Comment by yokofly** [comment]
discussed internally, this issue need consider the index, track https://github.com/timeplus-io/proton/issues/580
