### ISSUE TITLE
Sometimes dropping a materialized view takes too long

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#637]
**Describe what's wrong**

```sql
proton :) drop view mv2

DROP VIEW mv2

Query id: f72087ae-9e08-4ce4-af16-6e1550c814a0

Ok.

0 rows in set. Elapsed: 6.306 sec. 
```

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by yokofly** [comment]
can u provide a runnable case? or this is rare happen?

**Comment by yl-lisen** [comment]
When the mv internal pipeline fails and is waiting for recovery, it will take a long time to delete the mv.
