### ISSUE TITLE
MV recovery issue

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#646]
**Describe what's wrong**

A materialized view won't be able to properly recover if there were no data read from the source stream before the materialized view stopped. And when it starts again, it will read all data from the source stream.

**How to reproduce**

1. Create a stream `foo`.
2. Insert some data into the above `foo` stream, let's say 3 records are inserted.
3. Create a MV which read from `foo`, like `CREATE MATERIALIZED VIEW from_foo AS SELECT * FROM foo`.
4. *DO NOT* insert any new data into the `foo` stream.
5. There should be no data in the MV, i.e. `SELECT count(*) FROM table(from_foo)` should return `0`.
6. Terminate Proton.
7. Start Proton again.
8. I expect that the MV should still have no data, i.e. `SELECT count(*) FROM table(from_foo)` should still return `0`. However, the MV reads all the existing data from `foo`, thus, the SQL will return `3` instead of `0`.

**Error message and/or stacktrace**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
