### ISSUE TITLE
 versioned-kv join table(versioned-kv)

### ISSUE THREAD

**Issue by chenziliang** [timeplus-io/proton#657]
**Describe what's wrong**

versioned-kv join table(versioned-kv) is expected to be streaming and long running, but when the 2 versioned kv are empty, the query just exits

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

**Comment by yl-lisen** [comment]
If table(versioned-kv) is empty, exit this query (or throw an exception) is make sense instead of long running, since there is always no result.
We can modify the behavior `throw an exception` to tell the user that an empty table exists
