### ISSUE TITLE
Proton Extenal Stream

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/proton#667]
One of our customer want to join two streams from different data centers.

One possible solution is to support external proton stream, similar like Kafka external stream or ClickHouse external table, user can create an external proton stream from Cluster A that will write the stream result into a stream on Cluster B in realtime.

**Comment by zliang-min** [comment]
Closed as duplicated: #208 #209

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
