### ISSUE TITLE
Get server_uuid via Proton REST API and SQL

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#707]
**Use case**

The proton server instance ID can be got via `DB::ServerUUID::get()` C++ code.
We'd like to call HTTP REST API and/or run SQL to get such server instance ID, so that we can better track usage and enforce license control for commercial product

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenziliang** [comment]
Closed in https://github.com/timeplus-io/proton/pull/731
