### ISSUE TITLE
Write to kafka external streams

### ISSUE THREAD

**Issue by zliang-min** [timeplus-io/proton#81]
**Use case**

Currently it's supported to create kafka external streams and read data directly from them. However, writing to such streams is not supported. It will be a very useful feature to send data to external streams so that users can easily use proton for real-time streaming processing, and send the data to other systems for different usage.

**Describe the solution you'd like**

Proton already supports specifying a target stream for materialized views, so we can use the same syntax for writing to external streams:

```sql
CREATE EXTERNAL STREAM some_stream ( ... );

CREATE MATERIALIZED VIEW some_view INTO some_stream AS ... ;
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
