### ISSUE TITLE
create a github action workflow support only check docs.(instead running long time to build codebase)

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#83]
**Use case**
Currently, if we propose a commit only related to docs, the whole project need rebuilt which takes one hour longer.

**Describe the solution you'd like**

Use the GitHub action workflow path filter to work with docs obviously.

```
Name: Documentation Check

on:
  push:
    branches:
      - 'docs/**'
    paths:
      - 'docs/**.md'
```

**Describe alternatives you've considered**

Use branch filter? if the whole PR **only modifies the docs**, do we need to declare this branch as titled with `docs/`?

**Additional context**
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

**Comment by qijun-niu-timeplus** [comment]
https://github.com/timeplus-io/proton/pull/124

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
