### ISSUE TITLE
Why is setting `group.id` in Kafka External Stream not possible?

### ISSUE THREAD

**Issue by szymonorz** [timeplus-io/proton#832]
Hey, I'm new to Proton so I might be missing something.

When I create an external stream that reads events from Kafka it gets a default consumer group name of `timeplus-source-<somehash>`. I was trying to figure out how to set it by hand and I saw that `group.id` is not allowed to be changed 
https://github.com/timeplus-io/proton/blob/870d7d55849c91bbc69265936d703bd77e2798c7/src/Storages/ExternalStream/Kafka/Kafka.cpp#L47
https://github.com/timeplus-io/proton/blob/870d7d55849c91bbc69265936d703bd77e2798c7/src/Storages/ExternalStream/Kafka/Kafka.cpp#L83

despite a comment in the exact same file giving an example of how to set `group.id` via `properties` setting 
https://github.com/timeplus-io/proton/blob/870d7d55849c91bbc69265936d703bd77e2798c7/src/Storages/ExternalStream/Kafka/Kafka.cpp#L157

Is there any reason as to why this is not allowed? Setting `group.id` makes monitoring easier when there are many streams set up.

**Comment by zliang-min** [comment]
Hi @szymonorz , sorry for the confusion. That comment in the code just shows the format for the `properties` setting ( apparently, it's not a good example, as it uses an unsupported property ).

Setting `"group.id"` is not allowed is because Kafka external streams do not use consumer groups, as we manage offset internally in proton.

I hope this helps.

**Comment by jovezhong** [comment]
@szymonorz mentioned  the consumer group name of `timeplus-source-<somehash>`. I am wondering whether you are using Timeplus Enterprise. If you create a Kafka integration via the UI, it will try to validate the connection and preview the results via Redpanda Connect and it will generate such consumer group. But when you create the integration, it will create a Kafka External Stream and read/write data without consumer group.

**Comment by szymonorz** [comment]
You're are correct, I'm using Timeplus Enterprise. So the consumer group is just the result of using the UI. 
Thanks for you answers

**Comment by jovezhong** [comment]
Feel free to join our https://timeplus.com/slack for more community support for Timeplus Enterprise.

The consumer group is only used during connection validation and data preview for the UI wizard.
