### ISSUE TITLE
hang in dict_get()

### ISSUE THREAD

**Issue by candlerb** [timeplus-io/proton#834]
I don't know how you want to treat this; the Proton documentation mentions [dict_get()](https://docs.timeplus.com/functions_for_comp#dict_get) but not `CREATE DICTIONARY`. One way or the other, I think either this functionality should be fixed and documented, or disabled.

**Describe what's wrong**

Following the [ip_trie dictionary example](https://clickhouse.com/docs/en/sql-reference/dictionaries#ip_trie) in the Clickhouse documentation, `dict_get()` hangs.

**How to reproduce**

This is a straightforward translation from Clickhouse to Proton syntax:

```
CREATE STREAM my_ip_addresses (
    prefix string,
    asn uint32,
    cca2 string
)
PRIMARY KEY prefix;

INSERT INTO my_ip_addresses(prefix,asn,cca2) VALUES
    ('202.79.32.0/20', 17501, 'NP'),
    ('2620:0:870::/48', 3856, 'US'),
    ('2a02:6b8:1::/48', 13238, 'RU'),
    ('2001:db8::/32', 65536, 'ZZ')
;

CREATE DICTIONARY my_ip_trie_dictionary (
    prefix string,
    asn uint32,
    cca2 string DEFAULT '??'
)
PRIMARY KEY prefix
SOURCE(CLICKHOUSE(TABLE 'my_ip_addresses'))
LAYOUT(IP_TRIE)
LIFETIME(3600);

SELECT dict_get('my_ip_trie_dictionary', 'cca2', to_ipv4('202.79.32.10')) AS result;
```

The `CREATE DICTIONARY` statement is unchanged apart from lowercasing the type names (e.g. String -> string)

**Error message and/or stacktrace**

After the final SELECT, Proton hangs. Hitting Ctrl-C requests termination of the query, but that also hangs. Pressing Ctrl-C a second time causes the CLI to exit.

```
brians-macbook-m3-pro.local :) SELECT dict_get('my_ip_trie_dictionary', 'cca2', to_ipv4('202.79.32.10')) AS result;

SELECT
  dict_get('my_ip_trie_dictionary', 'cca2', to_ipv4('202.79.32.10')) AS result

Query id: c9340426-98b2-4004-9d60-b2831dfb2722

^CCancelling query.
^C%
```

(No logs are shown from `proton server` when this select statement is issue)

**Additional context**

This is proton 1.5.17 running under macOS 14.6.2 on M3 Pro, installed via homebrew.

**Comment by jovezhong** [comment]
Hi @candlerb , thanks for reporting this.

Dictionary is not officially supported in Timeplus Proton yet. But we did fix an issue like this Dec 2023. https://github.com/timeplus-io/proton/pull/382 You may want to create the "base table" with MergeTree engine, as the example in the PR
```sql
CREATE stream if not exists geoip_t (
  cidr string,
  latitude float64,
  longitude float64,
  country_code string,
  state string,
  city string
) ENGINE = MergeTree ORDER BY cidr;
```
In your snippet
```
CREATE STREAM my_ip_addresses (
    prefix string,
    asn uint32,
    cca2 string
)
PRIMARY KEY prefix;
```
This is not a mutable stream and will use NativeLog and historical storage. This may not work with Dictionary.

You may try this, not sure whether it works. I probably should put some warning in the docs that `Dictionary` is not officially supported yet.

**Comment by candlerb** [comment]
This works, thanks:

```
DROP STREAM IF EXISTS my_ip_addresses;
CREATE STREAM my_ip_addresses (
    prefix string,
    asn uint32,
    cca2 string
)
ENGINE = MergeTree
PRIMARY KEY prefix
ORDER BY prefix;

INSERT INTO my_ip_addresses(prefix,asn,cca2) VALUES
    ('202.79.32.0/20', 17501, 'NP'),
    ('2620:0:870::/48', 3856, 'US'),
    ('2a02:6b8:1::/48', 13238, 'RU'),
    ('2001:db8::/32', 65536, 'ZZ')
;

DROP DICTIONARY my_ip_trie_dictionary;
CREATE DICTIONARY my_ip_trie_dictionary (
    prefix string,
    asn uint32,
    cca2 string DEFAULT '??'
)
PRIMARY KEY prefix
SOURCE(CLICKHOUSE(TABLE 'my_ip_addresses'))
LAYOUT(IP_TRIE)
LIFETIME(600);

SELECT dict_get('my_ip_trie_dictionary', 'cca2', to_ipv4('202.79.32.10')) AS result;
```

> This is not a mutable stream and will use NativeLog and historical storage

I don't quite get that. In the [architecture](https://docs.timeplus.com/proton-architecture) doc it says the default is NativeLog plus historical storage, but doesn't really explain what the other alternatives are, and what the benefits and limitations of each are.

> I probably should put some warning in the docs that `Dictionary` is not officially supported yet.

Perhaps simply remove the `dict_get()` function from the docs. If it wasn't there, I wouldn't have tried it :-)

**Comment by jovezhong** [comment]
Hi @candlerb , I have updated the doc to remove dict_get for now. When we officially support dictionary, I can add it back.

At the currently stage, we don't want to expose different engines directly to the end users. All "supported" type of storage are:
* append-only stream
* mutable stream
* versioned_kv and changelog_kv are still available in Timeplus Proton but may be replaced by mutable streams later this year
* external stream or external tables are technically different engines too

There are many more table engines in ClickHouse, some of them may work in Timeplus Proton too, such as Null or Memory. We are also looking to other table engines for external system integrations, such as postgres or s3. But we may implement them as external stream or external table to support streaming SQL. We will share more details when we decide the direction.

Again, thanks for trying this function and sharing the feedback. There are some community and commercial users who use Timeplus for DDoS detection and other IP related use cases. Feel free to join https://timeplus.com/slack to discuss more.
